'use client';
/**
 * The public showcase at `/analytics`.
 *
 * ── What this is, and what it deliberately is not ──────────────────────────
 * It renders the **same panel components** `/admin` renders, AnalyticsPanel,
 * ClicksPanel, ClickHeatmap, AudiencePanel, ChatPanel, CampaignsPanel,
 * SessionsPanel, against a committed sample dataset. Reusing them is the
 * whole design: a second set of "demo" panels would drift from the real ones,
 * and a showcase of a dashboard that no longer looks like the dashboard is
 * worse than no showcase.
 *
 * It is NOT the live panel with the auth removed. Real visitor data cannot go
 * here: `/admin` shows verbatim chatbot questions and a per-session table
 * carrying city, ASN organisation and a network prefix, at portfolio traffic
 * that combination identifies individuals, and the ASN is frequently an
 * employer. Publishing it would also contradict `/privacy`, which visitors
 * read on the understanding that the operator is the only audience.
 *
 * ── Why the panels are imported from components/admin/ ─────────────────────
 * Those files are pure presentation: each takes a payload prop and renders it.
 * None of them fetches, and none reads a credential, `lib/admin-client.ts` is
 * imported only by AdminShell, which this file does not use. So the boundary
 * that matters is "does it fetch", not "which folder is it in", and importing
 * the real panels here costs nothing while keeping them singular.
 *
 * The one thing that must never happen is this file gaining a `fetchAdmin`
 * call. It has no session and no token, so such a call would 404 forever, 
 * and, worse, it would mean a public page probing the gated API on every load.
 *
 * ── Why the data is a static import ────────────────────────────────────────
 * The page is statically rendered. There is no endpoint behind it, which is
 * also why every control's options are precomputed in the JSON rather than
 * derived on demand: the range presets and all 18 heatmap combinations exist
 * as baked payloads. See scripts/seed-analytics-demo.ts.
 */
import { useMemo, useState } from 'react';
import Link from 'next/link';
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar';
import { ADMIN_SECTIONS, adminSection } from '@/components/admin/admin-sections';
import { AdminNav } from '@/components/admin/AdminNav';
import { AdminSection } from '@/components/admin/AdminSection';
import { AnalyticsPanel } from '@/components/admin/AnalyticsPanel';
import { AudiencePanel } from '@/components/admin/AudiencePanel';
import { CampaignsPanel } from '@/components/admin/CampaignsPanel';
import { ChatPanel } from '@/components/admin/ChatPanel';
import { ClicksPanel } from '@/components/admin/ClicksPanel';
import {
  ClickHeatmap,
  type Device,
} from '@/components/admin/ClickHeatmap';
import { SessionsPanel } from '@/components/admin/SessionsPanel';
import { ThemeToggle } from '@/components/admin/ThemeToggle';
import { useAdminSectionNav } from '@/hooks/use-admin-section-nav';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  ToggleGroup,
  ToggleGroupItem,
} from '@/components/ui/toggle-group';
import type {
  Audience,
  Campaigns,
  ChatStats,
  ClickMap,
  Overview,
  SessionRow,
} from '@/lib/analytics/types';
import demo from '@/content/analytics-demo.json';

/** One range's worth of precomputed payloads. */
interface RangeBundle {
  overview: Overview;
  audience: Audience;
  campaigns: Campaigns;
  chat: ChatStats;
}

/**
 * The JSON is typed as `unknown`-ish by `resolveJsonModule`, which infers
 * literal types for every number and cannot know these are the query payloads.
 * Asserted once, here, rather than at seven use sites.
 *
 * The assertion is safe in the way that matters: the file is generated by
 * running the real query functions, whose return types *are* these interfaces.
 * If a payload shape changes, the generator changes with it.
 */
const RANGES = demo.ranges as unknown as Record<string, RangeBundle>;
const HEAT = demo.heat as unknown as Record<string, ClickMap>;
/**
 * One list, shared by every range.
 *
 * `listSessions` orders by last seen and all three windows end on the same
 * anchor date, so the newest rows are identical across them, stored once
 * rather than three times, which took 40 KB out of this page's bundle. The
 * generator asserts they really do match before deduplicating.
 */
const SESSION_ROWS = demo.sessionRows as unknown as SessionRow[];

const RANGE_OPTIONS = [
  { id: '7', label: '7 days' },
  { id: '30', label: '30 days' },
  { id: '90', label: '90 days' },
] as const;

/** `2026-09-09` as `9 September 2026`, without pulling in a date library. */
function prettyAnchor(key: string): string {
  const [y, m, d] = key.split('-').map(Number);
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June', 'July',
    'August', 'September', 'October', 'November', 'December',
  ];
  return `${d} ${months[m - 1]} ${y}`;
}

export function ShowcaseShell() {
  const [rangeId, setRangeId] = useState<string>('30');
  const [device, setDevice] = useState<Device>('desktop');
  const [kind, setKind] = useState<'click' | 'dead' | 'rage'>('click');
  const [mode, setMode] = useState<'resume' | 'immersive'>('resume');

  const bundle = RANGES[rangeId] ?? RANGES['30'];
  // Keyed by range as well as by the three controls, so changing the date
  // range moves the heatmap with every other panel instead of leaving one
  // stale figure on screen contradicting the rest.
  const heat = useMemo(
    () => HEAT[`${rangeId}:${device}:${kind}:${mode}`] ?? null,
    [rangeId, device, kind, mode],
  );

  const active = useAdminSectionNav(ADMIN_SECTIONS.map((s) => s.id));
  const anchor = prettyAnchor(demo.anchor);

  return (
    <SidebarProvider>
      <AdminNav active={active} />
      <SidebarInset>
        <header className="sticky top-0 z-20 flex flex-wrap items-center gap-2 border-b bg-background/95 px-4 py-3 backdrop-blur">
          <SidebarTrigger />
          <div className="min-w-0 flex-1">
            <p className="font-heading text-sm leading-tight">
              Portfolio analytics
              <Badge variant="secondary" className="ml-2 align-middle text-[10px]">
                Sample data
              </Badge>
            </p>
            <p className="truncate text-[11px] text-muted-foreground">
              {bundle.overview.meta.window.days} days to {anchor} · IST
            </p>
          </div>
          <ThemeToggle />
        </header>

        <main className="flex flex-col gap-8 px-4 py-5">
          <SampleNotice anchor={anchor} />

          {/* The range control. Deliberately not labelled "Last 7 days": these
              are windows into a fixed sample, and a relative label would be a
              lie the day after the file was generated. */}
          <div className="flex flex-wrap items-center gap-3">
            <span className="text-xs text-muted-foreground">Window</span>
            <ToggleGroup
              value={[rangeId]}
              onValueChange={(v) => {
                const next = v[0];
                if (next) setRangeId(next);
              }}
              className="flex-wrap"
            >
              {RANGE_OPTIONS.map((option) => (
                <ToggleGroupItem
                  key={option.id}
                  value={option.id}
                  className="text-xs"
                >
                  {option.label}
                </ToggleGroupItem>
              ))}
            </ToggleGroup>
            <span className="text-[11px] text-muted-foreground">
              ending {anchor}
            </span>
          </div>

          <AdminSection
            id="admin-overview"
            title={adminSection('admin-overview').label}
            blurb={adminSection('admin-overview').blurb}
          >
            <AnalyticsPanel data={bundle.overview} />
          </AdminSection>

          <AdminSection
            id="admin-clicks"
            title={adminSection('admin-clicks').label}
            blurb={adminSection('admin-clicks').blurb}
          >
            <ClicksPanel data={bundle.overview} />
          </AdminSection>

          <AdminSection
            id="admin-heatmap"
            title={adminSection('admin-heatmap').label}
            blurb={adminSection('admin-heatmap').blurb}
          >
            {/* `loading` is false and `error` null forever: the data is in the
                bundle, so there is nothing to wait for and nothing to fail.
                onRefresh is a no-op for the same reason, a Refresh button
                that re-renders identical data would imply the numbers move. */}
            <ClickHeatmap
              data={heat}
              device={device}
              kind={kind}
              mode={mode}
              loading={false}
              error={null}
              onDevice={setDevice}
              onKind={setKind}
              onMode={setMode}
              onRefresh={() => {}}
            />
          </AdminSection>

          <AdminSection
            id="admin-audience"
            title={adminSection('admin-audience').label}
            blurb={adminSection('admin-audience').blurb}
          >
            <AudiencePanel data={bundle.audience} />
          </AdminSection>

          <AdminSection
            id="admin-chat"
            title={adminSection('admin-chat').label}
            blurb={adminSection('admin-chat').blurb}
          >
            <ChatPanel data={bundle.chat} />
          </AdminSection>

          <AdminSection
            id="admin-campaigns"
            title={adminSection('admin-campaigns').label}
            blurb={adminSection('admin-campaigns').blurb}
          >
            <CampaignsPanel data={bundle.campaigns} />
          </AdminSection>

          <AdminSection
            id="admin-sessions"
            title={adminSection('admin-sessions').label}
            blurb={adminSection('admin-sessions').blurb}
          >
            <SessionsPanel rows={SESSION_ROWS} />
          </AdminSection>

          <HowItWorks />
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}

/**
 * The disclosure, above the numbers rather than below them.
 *
 * Placed first because a visitor who reads one thing on this page must read
 * this one: every figure below is fabricated, and a dashboard is exactly the
 * kind of artefact people assume is real. Saying so underneath would be a
 * footnote to a claim already made.
 */
function SampleNotice({ anchor }: { anchor: string }) {
  return (
    <div className="rounded-lg border border-[var(--color-chart-4)]/40 bg-[var(--color-chart-4)]/5 p-4">
      <p className="text-sm font-medium">
        Every number on this page is synthetic.
      </p>
      <p className="mt-1 text-xs text-muted-foreground">
        This is a working copy of my private analytics dashboard, running on{' '}
        {demo.totalSessions.toLocaleString('en-IN')} generated sessions over{' '}
        {demo.days} days ending {anchor}. No real visitor is represented, and
        nothing here was measured from anyone who read this site, including
        you. The panels, queries and charts are the production ones; only the
        rows underneath are invented.
      </p>
      <p className="mt-2 text-xs text-muted-foreground">
        The real dashboard is private, and stays private on purpose. It shows
        the text people type into the chat panel and a per-visit table with
        city and network operator, at this much traffic that is enough to
        identify someone, so it is not mine to publish. See{' '}
        <Link className="underline underline-offset-2" href="/privacy">
          the privacy page
        </Link>{' '}
        for what is actually collected, and how to switch it off.
      </p>
    </div>
  );
}

/** The engineering notes. The part an engineer reading this actually wants. */
function HowItWorks() {
  const notes: [string, string][] = [
    [
      'First-party, no third-party scripts',
      'No Google Analytics, no Tag Manager, no Clarity, no pixel of any ' +
        'kind. One 12 KB collector posting batched events to a Cloudflare ' +
        'Worker, and a D1 (SQLite) database behind it.',
    ],
    [
      'No IP address is ever stored',
      'Only a salted SHA-256 hash (used solely as a rate-limit key) plus a ' +
        'coarse /24 or /48 network prefix. The salt is required: an unsalted ' +
        'hash of the IPv4 space is reversible in minutes, so ingest refuses ' +
        'to write at all when it is unset.',
    ],
    [
      'Dwell is measured on leaving, not entering',
      'A section emits its page_view when the reader leaves it, carrying the ' +
        'time spent. Emitting on entry would mean every scroll past counted ' +
        'as a read, and the funnel would measure scrolling rather than ' +
        'attention.',
    ],
    [
      'Rates return null, not zero',
      'A click-through rate with nobody in the denominator is not 0%. It is ' +
        'undefined, and renders as a dash. Shown as 0% it invites the reader ' +
        'to conclude a step is broken when there was simply nothing to convert.',
    ],
    [
      'Days are pinned to IST',
      'Every daily bucket is UTC+5:30, never the database server’s idea of ' +
        'local time. Without that, "today" changes meaning depending on where ' +
        'the query ran.',
    ],
    [
      'Question text expires before the counts do',
      'The words people typed are deleted after 30 days; the counts, rates ' +
        'and coverage gaps survive to 180. Click coordinates go at 30 days too.',
    ],
  ];

  return (
    <section className="scroll-mt-2">
      <h2 className="font-heading text-lg leading-tight">How it works</h2>
      <p className="mt-0.5 text-xs text-muted-foreground">
        The decisions that took the longest, and why they went the way they did.
      </p>
      <dl className="mt-4 grid gap-4 sm:grid-cols-2">
        {notes.map(([title, body]) => (
          <div key={title} className="rounded-lg border bg-card p-3">
            <dt className="text-xs font-medium">{title}</dt>
            <dd className="mt-1 text-xs leading-relaxed text-muted-foreground">
              {body}
            </dd>
          </div>
        ))}
      </dl>
      <div className="mt-4 flex flex-wrap gap-2">
        <Button
          variant="outline"
          size="sm"
          className="text-xs"
          render={
            <a
              href="https://github.com/example-dev/portfolio/blob/main/ANALYTICS.md"
              target="_blank"
              rel="noreferrer noopener"
              data-track-tag="showcase-design-notes"
            >
              Read the design notes
            </a>
          }
        />
        <Button
          variant="ghost"
          size="sm"
          className="text-xs"
          render={
            <Link href="/privacy" data-track-tag="showcase-privacy">
              What gets collected
            </Link>
          }
        />
        <Button
          variant="ghost"
          size="sm"
          className="text-xs"
          render={
            <Link href="/" data-track-tag="showcase-home">
              Back to the portfolio
            </Link>
          }
        />
      </div>
      <footer className="pt-6 pb-8 text-[11px] text-muted-foreground">
        Sample data generated by <code>scripts/seed-analytics-demo.ts</code>,
        which pushes synthetic events through the same validation, ingest and
        SQL the live site uses, so these panels show real query output over
        invented rows, not hand-written figures.
      </footer>
    </section>
  );
}
