-- Generated by scripts/emit-migration.mjs — do not edit by hand.
-- Source of truth: lib/analytics/schema.ts (SCHEMA_VERSION 1).
-- Authoritative application is ensureSchema() at runtime; this file is a
-- belt for whichever migration mechanism the platform honours.
CREATE TABLE IF NOT EXISTS analytics_meta (
     key   TEXT PRIMARY KEY,
     value TEXT NOT NULL
   );
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS events (
     id              INTEGER PRIMARY KEY,
     session_id      TEXT    NOT NULL,
     visitor_id      TEXT,
     event           TEXT    NOT NULL,
     path            TEXT,
     section         TEXT,
     mode            TEXT,
     referrer        TEXT,
     referrer_host   TEXT,
     props           TEXT,
     viewport_w      INTEGER,
     viewport_h      INTEGER,
     device          TEXT,
     browser         TEXT,
     os              TEXT,
     duration_ms     INTEGER,
     seq             INTEGER,
     ip_hash         TEXT,
     ip_prefix       TEXT,
     is_internal     INTEGER NOT NULL DEFAULT 0,
     country         TEXT,
     region          TEXT,
     city            TEXT,
     asn_org         TEXT,
     utm_source      TEXT,
     utm_medium      TEXT,
     utm_campaign    TEXT,
     utm_content     TEXT,
     utm_term        TEXT,
     click_id        TEXT,
     click_id_source TEXT,
     landing_path    TEXT,
     created_at      INTEGER NOT NULL
   );
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS events_created_idx ON events (created_at);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS events_event_created_idx
     ON events (event, created_at);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS events_session_order_idx
     ON events (session_id, created_at, seq);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS events_visitor_created_idx
     ON events (visitor_id, created_at);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS events_section_created_idx
     ON events (section, created_at);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS click_points (
     id          INTEGER PRIMARY KEY,
     session_id  TEXT    NOT NULL,
     path        TEXT    NOT NULL,
     section     TEXT,
     mode        TEXT,
     device      TEXT,
     viewport_w  INTEGER,
     viewport_h  INTEGER,
     x_pct       REAL    NOT NULL,
     y_pct       REAL    NOT NULL,
     doc_h       INTEGER,
     selector    TEXT,
     kind        TEXT    NOT NULL DEFAULT 'click',
     is_internal INTEGER NOT NULL DEFAULT 0,
     created_at  INTEGER NOT NULL
   );
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS click_points_kind_idx
     ON click_points (kind, created_at);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS click_points_created_idx
     ON click_points (created_at);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS chat_health (
     day                 TEXT PRIMARY KEY,
     requests            INTEGER NOT NULL DEFAULT 0,
     backend_configured  INTEGER NOT NULL DEFAULT 0,
     backend_ok          INTEGER NOT NULL DEFAULT 0,
     backend_fail        INTEGER NOT NULL DEFAULT 0,
     guard_short_circuit INTEGER NOT NULL DEFAULT 0
   );
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS ingest_budget (
     bucket       TEXT PRIMARY KEY,
     window_start INTEGER NOT NULL,
     events       INTEGER NOT NULL
   );
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS ingest_budget_window_idx
     ON ingest_budget (window_start);
