-- Generated by scripts/emit-migration.mjs. Do not edit by hand.
-- Source of truth: lib/analytics/schema.ts (SCHEMA_VERSION 2).
-- Authoritative application is ensureSchema() at runtime; this file is a
-- belt for whichever migration mechanism the platform honours.
CREATE TABLE IF NOT EXISTS chat_quota (
     bucket       TEXT PRIMARY KEY,
     window_start INTEGER NOT NULL,
     questions    INTEGER NOT NULL
   );
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS chat_quota_window_idx
     ON chat_quota (window_start);
