-- Generated by scripts/emit-migration.mjs. Do not edit by hand.
-- Source of truth: lib/analytics/schema.ts (SCHEMA_VERSION 3).
-- Authoritative application is ensureSchema() at runtime; this file is a
-- belt for whichever migration mechanism the platform honours.
CREATE TABLE IF NOT EXISTS trusted_networks (
     cidr      TEXT PRIMARY KEY,
     label     TEXT NOT NULL DEFAULT '',
     added_at  INTEGER NOT NULL,
     added_by  TEXT NOT NULL DEFAULT ''
   );
